# Generated by Django 6.0.3 on 2026-03-20 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SMARTPHONE', 'smartphone'), ('NOTEBOOK', 'notebooks'), ('SMART TV', 'smart tv')], max_length=15)),
                ('tensao', models.CharField(max_length=15)),
                ('dimensoes', models.CharField(max_length=15)),
                ('resolucao_tela', models.CharField(max_length=15)),
                ('armazenamento', models.CharField(max_length=15)),
                ('conectividade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('estoque_minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estoque_atual', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_transacao', models.CharField(choices=[('ENTRADA', 'entrada'), ('RETIRADA', 'retirada')], max_length=15)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='api.produto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='api.usuario')),
            ],
        ),
    ]
